name: E2E - Playwright/Cucumber

on:
  push:
    branches: ["main", "master"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    defaults:
      run:
        working-directory: e2e

    env:
      CI: "true"
      NODE_ENV: localhost
      COMMON_CONFIG_FILE: settings/settings.env
      HEADLESS: "true"


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: e2e/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Optional: useful if you rely on OS deps/fonts/etc.
      # - name: Install OS deps only (alt)
      #   run: npx playwright install-deps

      - name: Run smoke tests
        run: npm run cucumber:localhost -- --tags "@smoke"
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          # Example:
          GENERIC_API_KEY: ${{ secrets.GENERIC_API_KEY }}


      - name: Upload reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-artifacts
          retention-days: 14
          if-no-files-found: warn
          path: |
            e2e/reports/**
            e2e/test-results/**
            e2e/playwright-report/**
            e2e/screenshots/**
            e2e/logs/**
